---
  - name: remove pip library 
    hosts: jenkinsagents
    become: yes
    become_method: sudo

    tasks:
     - name:
       pip: name={{item}} state=absent
       with_items:
       - enum
       - enum34

